<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Permission::insert([
            ['name' => 'created task' ,'description' => 'create tasks'],
            ['name' => 'login' ,'description' => 'login'],
            ['name' => 'register' ,'description' => 'register'],
            ['name' => 'logout' ,'description' => 'logout'],
            ['name' => 'update task' ,'description' => 'update tasks'],
            ['name' => 'delete task' ,'description' => 'delete tasks'],
            ['name' => 'view task' ,'description' => 'view tasks'],
            ['name' => 'view users' ,'description' => 'view users'],
            ['name' => 'delete users' ,'description' => 'delete users'],
            ['name' => 'update users' ,'description' => 'update users'],
            ['name' => 'create users' ,'description' => 'create users'],
            ['name' => 'view roles' ,'description' => 'view roles'],
            ['name' => 'delete roles' ,'description' => 'delete roles'],
            ['name' => 'update roles' ,'description' => 'update roles'],
            ['name' => 'create roles' ,'description' => 'create roles'],
            ['name' => 'view permissions' ,'description' => 'view permissions'],
            ['name' => 'delete permissions' ,'description' => 'delete permissions'],
            ['name' => 'update permissions' ,'description' => 'update permissions'],
            ['name' => 'create permissions' ,'description' => 'create permissions'],
            ['name' => 'view products' ,'description' => 'view products'],
            ['name' => 'delete products' ,'description' => 'delete products'],
            ['name' => 'update products' ,'description' => 'update products'],
            ['name' => 'create products' ,'description' => 'create products'],
            ['name' => 'view categories' ,'description' => 'view categories'],
            ['name' => 'delete categories' ,'description' => 'delete categories'],
            ['name' => 'update categories' ,'description' => 'update categories'],
            ['name' => 'create categories' ,'description' => 'create categories'],
            ['name' => 'view orders' ,'description' => 'view orders'],
            ['name' => 'delete orders' ,'description' => 'delete orders'],
            ['name' => 'update orders' ,'description' => 'update orders'],
            ['name' => 'create orders' ,'description' => 'create orders'],
            ['name' => 'view customers' ,'description' => 'view customers'],
            ['name' => 'delete customers' ,'description' => 'delete customers'],
            ['name' => 'update customers' ,'description' => 'update customers'],
            ['name' => 'create customers' ,'description' => 'create customers'],
            ['name' => 'view suppliers' ,'description' => 'view suppliers'],
            ['name' => 'delete suppliers' ,'description' => 'delete suppliers'],
            ['name' => 'update suppliers' ,'description' => 'update suppliers'],
            ['name' => 'create suppliers' ,'description' => 'create suppliers'],
            ['name' => 'view employees' ,'description' => 'view employees'],
            ['name' => 'delete employees' ,'description' => 'delete employees'],
            ['name' => 'update employees' ,'description' => 'update employees'],
            ['name' => 'create employees' ,'description' => 'create employees'],
            ['name' => 'view departments' ,'description' => 'view departments'],
            ['name' => 'delete departments' ,'description' => 'delete departments'],
            ['name' => 'update departments' ,'description' => 'update departments'],
            ['name' => 'create departments' ,'description' => 'create departments'],
            ['name' => 'view positions' ,'description' => 'view positions'],
            ['name' => 'delete positions' ,'description' => 'delete positions'],
            ['name' => 'update positions' ,'description' => 'update positions'],
            ['name' => 'create positions' ,'description' => 'create positions'],
            ['name' => 'view attendance' ,'description' => 'view attendance'],
            ['name' => 'delete attendance' ,'description' => 'delete attendance'],
            ['name' => 'update attendance' ,'description' => 'update attendance'],
            ['name' => 'create attendance' ,'description' => 'create attendance'],
            ['name' => 'view leave' ,'description' => 'view leave'],
            ['name' => 'delete leave' ,'description' => 'delete leave'],
            ['name' => 'update leave' ,'description' => 'update leave'],
            ['name' => 'create leave' ,'description' => 'create leave'],
            ['name' => 'view payroll' ,'description' => 'view payroll'],
            ['name' => 'delete payroll' ,'description' => 'delete payroll'],
            ['name' => 'update payroll' ,'description' => 'update payroll'],
            ['name' => 'create payroll' ,'description' => 'create payroll'],
            ['name' => 'view expenses' ,'description' => 'view expenses'],
            ['name' => 'delete expenses' ,'description' => 'delete expenses'],
            ['name' => 'update expenses' ,'description' => 'update expenses'],
            ['name' => 'create expenses' ,'description' => 'create expenses'],
            ['name' => 'view income' ,'description' => 'view income'],
            ['name' => 'delete income' ,'description' => 'delete income'],
            ['name' => 'update income' ,'description' => 'update income'],
            ['name' => 'create income' ,'description' => 'create income'],
            ['name' => 'view reports' ,'description' => 'view reports'],
            ['name' => 'delete reports' ,'description' => 'delete reports'],
            ['name' => 'update reports' ,'description' => 'update reports'],
            ['name' => 'create reports' ,'description' => 'create reports'],
            ['name' => 'view settings' ,'description' => 'view settings'],
            ['name' => 'delete settings' ,'description' => 'delete settings'],
            ['name' => 'update settings' ,'description' => 'update settings'],
            ['name' => 'create settings' ,'description' => 'create settings'],
        ]);
    }
}
