-- SQL Practice Challenges
-- 1. Select all columns from the 'users' table.

select * from users;

-- 2. List the names and email addresses of all users.

select name, email from users;

-- 3. Find all companies located in a specific city.

select * from companies where city = 'casablanca';

-- 4. Select the name and price of all products.

select name, price from products;

-- 5. List all unique categories available in the products table.

select distinct category from products;

-- 6. Retrieve the first 10 orders placed.

select * from orders limit 10;

-- 7. Count the total number of clients in the 'clients' table.

select count(*) from clients;

-- 8. Find the maximum price of a product.

select max(price) from products;

-- 9. Find the average total amount of all orders.

select avg(total_amount) from orders;

-- 10. List all users who joined in the last 30 days.

select * from users where created_at >= now() - interval '30 days';

-- 11. Select all products with a price greater than 100.

select * from products where price > 100;

-- 12. Find all orders with a status of 'pending'.

select * from orders where status = 'pending';

-- 13. List all clients whose name starts with the letter 'A'.
-- 14. Retrieve all products that are out of stock (stock = 0).
-- 15. Find all users who do not have a phone number assigned.
-- 16. Select all orders placed on a specific date (e.g., '2023-05-01').
-- 17. List all products sorted by price in descending order.
-- 18. Find all companies that were created in 2024.
-- 19. Retrieve the names of clients who live in 'New York'.
-- 20. Count how many orders were cancelled.

-- 21. Select all products with price between 50 and 150.
-- 22. List all users whose email domain is 'gmail.com'.
-- 23. Find all orders with a total amount greater than the average total amount.
-- 24. Retrieve the top 5 most expensive products.
-- 25. Select all clients who have placed at least one order.
-- 26. Find all products that belong to category ID 5.
-- 27. List all users and sort them by their last name.
-- 28. Retrieve all items in a specific order (ID 101).
-- 29. Find the total stock across all products.
-- 30. List all orders that have notes attached.

-- 31. Join 'users' and 'companies' to show which user belongs to which company.
-- 32. Show all orders along with the name of the client who placed them.
-- 33. Retrieve all products and their category names.
-- 34. List all orders and the name of the supplier assigned to them.
-- 35. Show a list of all order items with the corresponding product name and price.
-- 36. Find all clients who have never placed an order (using LEFT JOIN).
-- 37. List all companies and the count of users associated with each.
-- 38. Show the total amount spent by each client.
-- 39. Find the most popular product based on the total quantity sold.
-- 40. Retrieve all products that have never been ordered.

-- 41. Group orders by status and count how many are in each status.
-- 42. Find the total revenue generated by each company.
-- 43. Calculate the average product price per category.
-- 44. Group users by the month they joined and count them.
-- 45. Find the total number of items sold for each product.
-- 46. List categories that have more than 10 products.
-- 47. Find clients who have spent more than $1000 in total.
-- 48. Show the daily total sales for the last 7 days.
-- 49. Calculate the profit margin for each product (price - cost).
-- 50. Find the maximum order amount for each month.

-- 51. Retrieve users who have the role 'administrator' (join with roles table if exists).
-- 52. Show the names of products that have a stock lower than the average stock.
-- 53. Find all orders that contain more than 5 line items.
-- 54. List all companies and their latest order date.
-- 55. Find the client who has placed the highest number of orders.
-- 56. Retrieve the second most expensive product (using OFFSET).
-- 57. Show all products that have been updated since they were created.
-- 58. Find the total number of orders placed by each user.
-- 59. List all products that are supplied by 'Supplier X'.
-- 60. Show the percentage of orders that are 'shipped' vs total orders.

-- 61. Subquery: Find products that have a price higher than the price of 'Product A'.
-- 62. Subquery: List all clients who placed an order in the same month as 'Client Y'.
-- 63. Subquery: Find the IDs of orders that contain the product 'Widget 1'.
-- 64. EXISTS: Find companies that have at least one product with stock > 100.
-- 65. IN: List all users who belong to companies in the 'Europe' region.
-- 66. CTE: Create a temporary result set of top 10 clients and select from it.
-- 67. Window Function: Rank products by price within each category.
-- 68. Window Function: Show a running total of daily sales.
-- 69. Window Function: Find the difference in price between a product and the one before it.
-- 70. CASE: Categorize products as 'Cheap', 'Moderate', or 'Expensive' based on price.

-- 71. Update the status of all orders older than 6 months to 'archived'.
-- 72. Increase the price of all products in category 3 by 10%.
-- 73. Delete all users who have not logged in for over a year (Soft delete check).
-- 74. Insert a new client record into the clients table.
-- 75. Change the company name for a specific company ID.
-- 76. Update stock levels after a new shipment is received.
-- 77. Remove all orders that were cancelled and are older than 30 days.
-- 78. Set the 'notes' field to empty for all orders that currently have NULL.
-- 79. Assign a default supplier to all products that don't have one.
-- 80. Mark all delivered orders as 'paid' (if payment_status exists).

-- 81. Find the path/hierarchy of categories (if recursive).
-- 82. Retrieve the last 3 orders for every client.
-- 83. Find products that are frequently bought together (Association).
-- 84. Calculate the time difference between order_date and delivery_date.
-- 85. List users who have permissions to 'manage_orders'.
-- 86. Find the average number of items per order.
-- 87. Show the most active time of day for order placement.
-- 88. Identify any duplicate product SKUs.
-- 89. Retrieve all deleted records (from SoftDeletes).
-- 90. Find the total weight of an order (if weight column exists).

-- 91. Select the name of the company with the highest overall sales.
-- 92. Find users who have invited other users (if invitations table exists).
-- 93. List all products that have zero sales in the last quarter.
-- 94. Calculate the churn rate of clients over the last year.
-- 95. Find the gap in auto-increment IDs for the orders table.
-- 96. Show the names of users who joined on a weekend.
-- 97. Retrieve the top 3 categories by revenue.
-- 98. Find the average order value (AOV) for each company.
-- 99. List all products that share the same price.

select name, price
from products
where price in (select price from products group by price having count(*) > 1);

-- 100. Select the count of orders for each day of the week.

select to_char(created_at, 'Day') as day, count(*) as count
from orders
where created_at >= now() - interval '1 week'
group by day
order by count desc;


-- 101. List all users and the name of the company they belong to, along with their role.

select u.name, c.name ,r.name
from users u 
join membership m on u.id = m.user_id
join companies c on m.company_id = c.id
join roles r on m.role_id = r.id;
